spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/lavender
    username: lavender
    password: lavender
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
#    hibernate:
#      ddl-auto: create
#  jackson:
#    serialization:
#     WRITE_DATES_AS_TIMESTAMPS: false
